<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Add New Product
        </h2>
    </x-slot>

    <!-- Quill Editor CSS -->
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

    <div class="py-6 h-[calc(100vh-65px)] overflow-hidden">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 h-full flex flex-col">
            <div class="bg-white rounded-xl shadow-sm border border-gray-200 flex-grow flex flex-col overflow-hidden">
                
                <form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data" class="flex flex-col h-full" id="product-form">
                    @csrf
                    
                    <div class="flex-grow flex flex-col md:flex-row overflow-hidden">
                        
                        <!-- Left Panel: Tech & Pricing -->
                        <div class="w-full md:w-1/2 p-4 md:p-5 overflow-y-auto border-r border-gray-100 scrollbar-hide">
                            <h3 class="text-sm font-bold text-brand-700 uppercase tracking-wider mb-3 border-b pb-1">Data Utama</h3>
                            
                            <!-- Kategori & Basic Info -->
                            <div class="grid grid-cols-2 gap-3 mb-3">
                                <div>
                                    <label class="block text-[11px] font-bold text-gray-600 mb-1">Kategori *</label>
                                    <select name="category_id" required class="w-full px-2 py-1.5 text-xs border border-gray-300 rounded focus:ring-1 focus:ring-brand-500 focus:border-brand-500">
                                        <option value="">Pilih Kategori</option>
                                        @foreach(\App\Models\Category::whereNull('parent_id')->with('children')->get() as $parentCat)
                                            <optgroup label="{{ $parentCat->name }}">
                                                @foreach($parentCat->children as $childCat)
                                                    <option value="{{ $childCat->id }}" data-type="{{ $childCat->type_category }}" {{ old('category_id') == $childCat->id ? 'selected' : '' }}>
                                                        {{ $childCat->name }}
                                                    </option>
                                                @endforeach
                                            </optgroup>
                                        @endforeach
                                    </select>
                                </div>
                                <div>
                                    <label class="block text-[11px] font-bold text-gray-600 mb-1">Unit ID / SKU *</label>
                                    <input type="text" name="serial_number" required readonly value="{{ $autoGeneratedId }}" class="w-full px-2 py-1.5 text-xs border border-gray-300 rounded bg-gray-100 focus:outline-none cursor-not-allowed">
                                </div>
                                <div>
                                    <label class="block text-[11px] font-bold text-gray-600 mb-1">Brand *</label>
                                    <input type="text" name="brand" required class="w-full px-2 py-1.5 text-xs border border-gray-300 rounded focus:ring-1 focus:ring-brand-500" placeholder="ASUS">
                                </div>
                                <div>
                                    <label class="block text-[11px] font-bold text-gray-600 mb-1">Model Series *</label>
                                    <input type="text" name="model_series" required class="w-full px-2 py-1.5 text-xs border border-gray-300 rounded focus:ring-1 focus:ring-brand-500" placeholder="ROG G15">
                                </div>
                            </div>

                            <h3 class="text-sm font-bold text-brand-700 uppercase tracking-wider mb-3 border-b pb-1 mt-4">Spesifikasi Teknis</h3>
                            <!-- Spesifikasi (4 Cols) -->
                            <div id="spesifikasi-teknis-section" class="grid grid-cols-2 md:grid-cols-4 gap-3 mb-3">
                                <div class="col-span-2">
                                    <label class="block text-[11px] font-bold text-gray-600 mb-1">Processor</label>
                                    <input type="text" name="processor" class="w-full px-2 py-1.5 text-xs border border-gray-300 rounded focus:ring-1 focus:ring-brand-500" placeholder="i7-11800H">
                                </div>
                                <div>
                                    <label class="block text-[11px] font-bold text-gray-600 mb-1">RAM</label>
                                    <input type="text" name="ram" class="w-full px-2 py-1.5 text-xs border border-gray-300 rounded focus:ring-1 focus:ring-brand-500" placeholder="16GB">
                                </div>
                                <div>
                                    <label class="block text-[11px] font-bold text-gray-600 mb-1">Storage</label>
                                    <input type="text" name="storage" class="w-full px-2 py-1.5 text-xs border border-gray-300 rounded focus:ring-1 focus:ring-brand-500" placeholder="512GB SSD">
                                </div>
                                <div>
                                    <label class="block text-[11px] font-bold text-gray-600 mb-1">Layar (Inch)</label>
                                    <input type="number" step="0.1" name="screen_size" class="w-full px-2 py-1.5 text-xs border border-gray-300 rounded focus:ring-1 focus:ring-brand-500" placeholder="15.6">
                                </div>
                                <div>
                                    <label class="block text-[11px] font-bold text-gray-600 mb-1">Daya Tahan Baterai (Jam)</label>
                                    <input type="number" step="0.1" name="battery_runtime" class="w-full px-2 py-1.5 text-xs border border-gray-300 rounded focus:ring-1 focus:ring-brand-500" placeholder="2.5">
                                </div>
                                <div class="col-span-2">
                                    <label class="block text-[11px] font-bold text-gray-600 mb-1">Kondisi *</label>
                                    <select name="condition" required class="w-full px-2 py-1.5 text-xs border border-gray-300 rounded focus:ring-1 focus:ring-brand-500">
                                        <option value="Baru">Baru</option>
                                        <option value="Bekas" selected>Bekas</option>
                                        <option value="Mulus">Mulus</option>
                                    </select>
                                </div>
                            </div>

                            <div id="inventaris-harga-section">
                                <h3 class="text-sm font-bold text-brand-700 uppercase tracking-wider mb-3 border-b pb-1 mt-4">Inventaris & Harga</h3>

                                {{-- Baris 1: Tipe Stok & QTY --}}
                                <div class="grid grid-cols-3 gap-3 mb-3">
                                    <label class="flex items-center gap-2 p-2 border-2 rounded cursor-pointer transition-all has-[:checked]:border-emerald-500 has-[:checked]:bg-emerald-50 border-gray-200">
                                        <input type="radio" name="tipe_stok" value="ready_stock" checked class="accent-emerald-500">
                                        <div>
                                            <p class="text-[11px] font-bold text-gray-700">Ready Stock</p>
                                            <p class="text-[9px] text-gray-400">Tersedia fisik</p>
                                        </div>
                                    </label>
                                    <label class="flex items-center gap-2 p-2 border-2 rounded cursor-pointer transition-all has-[:checked]:border-orange-500 has-[:checked]:bg-orange-50 border-gray-200">
                                        <input type="radio" name="tipe_stok" value="open_order" class="accent-orange-500">
                                        <div>
                                            <p class="text-[11px] font-bold text-gray-700">Open Order</p>
                                            <p class="text-[9px] text-gray-400">Pre-order / indent</p>
                                        </div>
                                    </label>
                                    <div id="stock-qty-container">
                                        <label class="block text-[11px] font-bold text-gray-600 mb-1">Stok QTY *</label>
                                        <input type="number" name="stock" required min="0" value="1" class="w-full px-2 py-1.5 text-xs border border-gray-300 rounded focus:ring-1 focus:ring-brand-500 font-bold text-brand-700">
                                        <input type="hidden" name="status" value="available">
                                    </div>
                                </div>

                                {{-- Baris 2: Harga --}}
                                <div class="grid grid-cols-4 gap-3">
                                    <div>
                                        <label class="block text-[11px] font-bold text-gray-600 mb-1">Harga Beli *</label>
                                        <input type="number" name="purchase_price" required class="w-full px-2 py-1.5 text-xs border border-gray-300 rounded focus:ring-1 focus:ring-brand-500 text-red-600 font-bold">
                                    </div>
                                    <div>
                                        <label class="block text-[11px] font-bold text-gray-600 mb-1">Biaya Ops.</label>
                                        <input type="number" name="operational_cost" class="w-full px-2 py-1.5 text-xs border border-gray-300 rounded focus:ring-1 focus:ring-brand-500" value="0">
                                    </div>
                                    <div>
                                        <label class="block text-[11px] font-bold text-gray-600 mb-1">Harga Jual *</label>
                                        <input type="number" name="selling_price" required class="w-full px-2 py-1.5 text-xs border border-gray-300 rounded focus:ring-1 focus:ring-brand-500 text-emerald-600 font-bold">
                                    </div>
                                    <div>
                                        <label class="block text-[11px] font-bold text-gray-600 mb-1">Harga Coret (Opsional)</label>
                                        <input type="number" name="original_price" class="w-full px-2 py-1.5 text-xs border border-gray-300 rounded focus:ring-1 focus:ring-brand-500 text-gray-500 font-bold" placeholder="Cth: 5000000">
                                    </div>
                                </div>

                                {{-- KEPEMILIKAN ASET --}}
                                <div x-data="{ ownerType: '{{ old('ownership_type', 'lktech') }}' }" class="mt-3 p-3 bg-violet-50 rounded-xl border border-violet-100">
                                    <p class="text-[11px] font-black text-violet-700 uppercase tracking-wider mb-2">Kepemilikan Aset</p>
                                    <div class="flex gap-2 mb-2">
                                        <label class="flex items-center gap-1.5 px-3 py-1.5 border-2 rounded-lg cursor-pointer transition-all text-[11px] font-bold"
                                               :class="ownerType === 'lktech' ? 'border-brand-500 bg-brand-50 text-brand-700' : 'border-gray-200 text-gray-600'">
                                            <input type="radio" name="ownership_type" value="lktech" x-model="ownerType" checked class="sr-only">
                                            🏢 Milik LKTech
                                        </label>
                                        <label class="flex items-center gap-1.5 px-3 py-1.5 border-2 rounded-lg cursor-pointer transition-all text-[11px] font-bold"
                                               :class="ownerType === 'investor' ? 'border-violet-500 bg-violet-50 text-violet-700' : 'border-gray-200 text-gray-600'">
                                            <input type="radio" name="ownership_type" value="investor" x-model="ownerType" class="sr-only">
                                            👤 Milik Investor
                                        </label>
                                    </div>
                                    <div x-show="ownerType === 'investor'" x-transition>
                                        <label class="block text-[10px] font-bold text-violet-600 mb-1">Pilih Investor</label>
                                        <select name="investor_id" class="w-full px-2 py-1.5 text-xs border border-violet-300 rounded focus:ring-1 focus:ring-violet-500">
                                            <option value="">-- Pilih Investor --</option>
                                            @foreach($investors as $inv)
                                            <option value="{{ $inv->id }}" {{ old('investor_id') == $inv->id ? 'selected' : '' }}>
                                                {{ $inv->name }} ({{ number_format($inv->share_percentage, 1) }}%)
                                            </option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Right Panel: Catalog Visuals -->
                        <div class="w-full md:w-1/2 p-4 md:p-5 overflow-y-auto bg-gray-50 scrollbar-hide">
                            <h3 class="text-sm font-bold text-fuchsia-700 uppercase tracking-wider mb-3 border-b border-fuchsia-200 pb-1">Visual Katalog</h3>
                            
                            <!-- Banner Promo Toggle -->
                            <div class="mb-4 bg-white p-3 rounded-lg border border-fuchsia-100 shadow-sm flex flex-col gap-3">
                                <label class="flex items-start gap-3 cursor-pointer">
                                    <div class="pt-0.5">
                                        <input type="checkbox" name="is_banner_hero" value="1" class="w-4 h-4 text-fuchsia-600 border-gray-300 rounded focus:ring-fuchsia-500">
                                    </div>
                                    <div>
                                        <span class="block text-xs font-bold text-gray-800">Tampilkan sebagai Banner Promo (Hero Slider)</span>
                                        <span class="block text-[10px] text-gray-500 leading-tight mt-0.5">Produk ini akan tampil pada kartu sliding hero di bagian atas landing page.</span>
                                    </div>
                                </label>
                                
                                <label class="flex items-start gap-3 cursor-pointer">
                                    <div class="pt-0.5">
                                        <input type="checkbox" name="is_promo_utama" value="1" class="w-4 h-4 text-red-600 border-gray-300 rounded focus:ring-red-500">
                                    </div>
                                    <div>
                                        <span class="block text-xs font-bold text-gray-800">Set sebagai Produk Promo Utama (🔥 Hot Promo)</span>
                                        <span class="block text-[10px] text-gray-500 leading-tight mt-0.5">Produk ini akan diberi badge 'Hot Promo' dan diprioritaskan tampil pada section Produk Promo di bawah banner.</span>
                                    </div>
                                </label>
                            </div>

                            <div class="mb-4">
                                <label class="block text-[11px] font-bold text-gray-600 mb-1">Video Preview (Opsional)</label>
                                <div class="flex gap-1 mb-1.5" id="video-tab-buttons">
                                    <button type="button" id="btn-tab-url" onclick="switchVideoTab('url')"
                                        class="flex-1 text-[10px] font-semibold py-1 rounded border border-brand-500 bg-brand-500 text-white transition">
                                        <i class='bx bxl-youtube mr-1'></i>Link YouTube
                                    </button>
                                    <button type="button" id="btn-tab-file" onclick="switchVideoTab('file')"
                                        class="flex-1 text-[10px] font-semibold py-1 rounded border border-gray-300 bg-white text-gray-600 transition">
                                        <i class='bx bx-upload mr-1'></i>Upload File
                                    </button>
                                </div>
                                {{-- Tab URL YouTube --}}
                                <div id="video-tab-url">
                                    <div class="relative">
                                        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                            <i class='bx bxl-youtube text-red-500'></i>
                                        </div>
                                        <input type="url" name="video_url" id="video_url_input"
                                            class="w-full pl-10 pr-3 py-2 bg-gray-50 border border-gray-200 rounded-lg focus:bg-white focus:border-brand-500 focus:ring-2 focus:ring-brand-200 transition-all text-sm outline-none shadow-sm"
                                            placeholder="Link Video (Contoh: https://youtube.com/...)">
                                    </div>
                                </div>
                                {{-- Tab Upload File Lokal --}}
                                <div id="video-tab-file" class="hidden">
                                    <label class="flex flex-col items-center justify-center w-full py-3 border-2 border-dashed border-gray-300 rounded-lg bg-gray-50 hover:bg-gray-100 cursor-pointer transition" id="video-upload-label">
                                        <i class='bx bx-video-plus text-2xl text-gray-400 mb-1'></i>
                                        <span class="text-[10px] text-gray-500" id="video-file-name">Klik untuk pilih video (MP4, WebM, MOV — maks 100MB)</span>
                                        <input type="file" name="video_file" id="video_file_input" class="hidden" accept="video/mp4,video/webm,video/quicktime,video/avi" onchange="previewVideoFile(event)">
                                    </label>
                                </div>
                            </div>

                            <div class="flex gap-4 mb-4">
                                <!-- Main Image Preview -->
                                <div class="w-1/3">
                                    <label class="block text-[11px] font-bold text-gray-600 mb-1">Foto Utama</label>
                                    <div class="relative w-full aspect-square bg-white rounded border-2 border-dashed border-gray-300 overflow-hidden flex items-center justify-center group h-[120px]" id="image-preview-container">
                                        <div class="text-center z-10 p-2" id="placeholder-text">
                                            <i class='bx bx-image-add text-2xl text-gray-400'></i>
                                            <p class="text-[9px] text-gray-500 mt-1">Klik Unggah</p>
                                        </div>
                                        <img src="" id="image-preview" class="absolute inset-0 w-full h-full object-contain bg-white sm:bg-gray-50 p-2 hidden">
                                        <input type="file" id="image-upload" name="image" class="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-20" accept="image/*" onchange="previewImage(event)">
                                    </div>
                                </div>
                                
                                <!-- Gallery Images Preview -->
                                <div class="w-2/3">
                                    <label class="block text-[11px] font-bold text-gray-600 mb-1">Galeri (Maks. 9)</label>
                                    <div class="grid grid-cols-4 gap-1.5 h-[120px] overflow-y-auto" id="gallery-preview-container">
                                        <label for="gallery-upload" class="relative w-full aspect-square bg-white rounded overflow-hidden border-2 border-dashed border-gray-300 hover:bg-gray-100 cursor-pointer flex flex-col items-center justify-center text-gray-400 transition" id="gallery-add-btn">
                                            <i class='bx bx-plus text-xl'></i>
                                            <input type='file' id="gallery-upload" name="gallery_images[]" class="hidden" accept="image/*" multiple onchange="previewGallery(event)" />
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div>
                                <label class="block text-[11px] font-bold text-gray-600 mb-1">Deskripsi Pemasaran</label>
                                <input type="hidden" name="description" id="description-input">
                                <div class="bg-white border border-gray-300 rounded overflow-hidden">
                                    <div id="editor" class="h-[150px] md:h-[200px] text-sm"></div>
                                </div>
                            </div>

                        </div>
                    </div>

                    <!-- Footer / Submit -->
                    <div class="bg-gray-100 border-t border-gray-200 p-3 flex justify-end gap-3 flex-shrink-0">
                        <a href="{{ route('products.index') }}" class="px-4 py-1.5 bg-white border border-gray-300 rounded text-sm font-semibold text-gray-600 hover:bg-gray-50">Batal</a>
                        <button type="submit" class="px-5 py-1.5 bg-brand-600 border border-brand-600 text-white rounded text-sm font-bold shadow hover:bg-brand-700 flex items-center gap-2">
                            <i class='bx bx-save'></i> Simpan Entri Baru
                        </button>
                    </div>

                </form>
            </div>
        </div>
    </div>
    
<script src="https://cdn.quilljs.com/1.3.6/quill.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function() {
    const categorySelect = document.querySelector('select[name="category_id"]');
    const specSection = document.getElementById('spesifikasi-teknis-section');
    const stockContainer = document.getElementById('stock-qty-container');
    const snLabel = document.querySelector('input[name="serial_number"]').previousElementSibling;
    const modelLabel = document.querySelector('input[name="model_series"]').previousElementSibling;
    const condCol = document.querySelector('select[name="condition"]').parentElement;

    function toggleSpecs() {
        if (!categorySelect || !specSection) return;
        const selectedOption = categorySelect.options[categorySelect.selectedIndex];
        const categoryType = selectedOption ? (selectedOption.getAttribute('data-type') || 'hardware') : 'hardware';

        if (categoryType === 'hardware') {
            specSection.style.display = 'grid';
            if(stockContainer) stockContainer.style.display = 'block';
            snLabel.textContent = 'Unit ID / SKU *';
            modelLabel.textContent = 'Model Series *';
            condCol.style.display = 'block';
        } else if (categoryType === 'peripheral') {
            // Sembunyikan spesifikasi fisik, tetapi keep stock
            specSection.style.display = 'none';
            if(stockContainer) stockContainer.style.display = 'block';
            snLabel.textContent = 'Unit ID / SKU *';
            modelLabel.textContent = 'Model Series *';
            condCol.style.display = 'none';
        } else if (categoryType === 'software') {
            // Sembunyikan spesifikasi fisik, tetapi keep stock
            specSection.style.display = 'none';
            if(stockContainer) stockContainer.style.display = 'block';
            snLabel.textContent = 'Unit ID / SKU *';
            modelLabel.textContent = 'Tipe Lisensi *';
            condCol.style.display = 'none';
        } else if (categoryType === 'service') {
            // Sembunyikan spesifikasi fisik dan stok
            specSection.style.display = 'none';
            if(stockContainer) stockContainer.style.display = 'none';
            snLabel.textContent = 'Unit ID / SKU *';
            modelLabel.textContent = 'Tipe Jasa *';
            condCol.style.display = 'none';
        } else {
            // Default (misal hardware tapi gak diset)
            specSection.style.display = 'grid';
            if(stockContainer) stockContainer.style.display = 'block';
            snLabel.textContent = 'Unit ID / SKU *';
            modelLabel.textContent = 'Model Series *';
            condCol.style.display = 'block';
        }
    }

    if (categorySelect) {
        categorySelect.addEventListener('change', () => {
            toggleSpecs();
            calculateSellingPrice();
        });
        toggleSpecs(); 
    }

    const purchasePriceInput = document.querySelector('input[name="purchase_price"]');
    const sellingPriceInput = document.querySelector('input[name="selling_price"]');

    function calculateSellingPrice() {
        if (!categorySelect || !purchasePriceInput || !sellingPriceInput) return;
        const selectedOption = categorySelect.options[categorySelect.selectedIndex];
        if (!selectedOption || !selectedOption.value) return;

        const categoryName = selectedOption.text.trim().toLowerCase();
        const categoryType = selectedOption.getAttribute('data-type');
        let purchasePrice = parseFloat(purchasePriceInput.value) || 0;
        let sellingPrice = 0;

        if (categoryType === 'service') {
            purchasePriceInput.value = 0;
            if (categoryName.includes('instalasi')) {
                sellingPrice = 150000;
            } else if (categoryName.includes('perbaikan') || categoryName.includes('service')) {
                sellingPrice = 200000;
            } else if (categoryName.includes('website')) {
                sellingPrice = 500000;
            } else if (categoryName.includes('aplikasi')) {
                sellingPrice = 1000000;
            }
        } else if (categoryType === 'software') {
            sellingPrice = purchasePrice * 1.5;
        } else {
            if (purchasePrice <= 1999999) {
                sellingPrice = purchasePrice * 1.4;
            } else if (purchasePrice <= 2999999) {
                sellingPrice = purchasePrice * 1.35;
            } else if (purchasePrice <= 3999999) {
                sellingPrice = purchasePrice * 1.3;
            } else if (purchasePrice <= 4999999) {
                sellingPrice = purchasePrice * 1.25;
            } else {
                sellingPrice = purchasePrice * 1.2;
            }
        }

        sellingPriceInput.value = Math.round(sellingPrice);
    }

    if (purchasePriceInput) {
        purchasePriceInput.addEventListener('input', calculateSellingPrice);
    }

    // Quill Minimalist Initialization
    var quill = new Quill('#editor', {
        theme: 'snow',
        placeholder: 'Ketik spesifikasi lengkap (contoh: Lenovo Thinkpad, Intel Core i7-8665U, 16GB RAM, 512GB SSD, 14 inch)...',
        modules: {
            toolbar: [
                ['bold', 'italic', 'underline', 'strike'],
                [{ 'list': 'bullet' }]
            ]
        }
    });

    quill.on('text-change', function() {
        const text = quill.getText();
        
        // Brand Parsing
        const brands = ['Lenovo', 'HP', 'Dell', 'Asus', 'Acer', 'Apple', 'MSI', 'MacBook', 'ThinkPad', 'ROG'];
        const brandMatch = text.match(new RegExp("(" + brands.join('|') + ")", "i"));
        if(brandMatch) document.querySelector('[name="brand"]').value = brandMatch[0];

        // Processor Parsing
        const procMatch = text.match(/(Intel Core i\d-[a-zA-Z0-9]+|Intel[\w\s]+|AMD Ryzen \d \d+[A-Z]*|Apple M[1-3][\w\s]*)/i);
        if(procMatch) document.querySelector('[name="processor"]').value = procMatch[0].trim();

        // RAM Parsing
        const ramMatch = text.match(/(\d+\s*GB)\s*(DDR\d|RAM|LPDDR\d)?/i);
        if(ramMatch) document.querySelector('[name="ram"]').value = ramMatch[0].trim();

        // Storage Parsing
        const storageMatch = text.match(/(\d+\s*(GB|TB))\s*(SSD|HDD|NVMe|PCIe)/i);
        if(storageMatch) document.querySelector('[name="storage"]').value = storageMatch[0].trim();

        // Screen Size Parsing
        const screenMatch = text.match(/(\d+(\.\d+)?)\s*("|inch|'|inci)/i);
        if(screenMatch) document.querySelector('[name="screen_size"]').value = screenMatch[1];
    });

    document.getElementById('product-form').onsubmit = function() {
        document.getElementById('description-input').value = quill.root.innerHTML;
        // Inject data transfer files back to input before submit just in case
        document.getElementById('gallery-upload').files = galleryData.files;
    };
});

// Image Live Preview
function previewImage(event) {
    const file = event.target.files[0];
    const preview = document.getElementById('image-preview');
    const placeholder = document.getElementById('placeholder-text');
    
    if (file) {
        const reader = new FileReader();
        reader.onload = function(e) {
            preview.src = e.target.result;
            preview.classList.remove('hidden');
            if(placeholder) placeholder.style.display = 'none';
        }
        reader.readAsDataURL(file);
    }
}

let galleryData = new DataTransfer();

function previewGallery(event) {
    const files = event.target.files;
    
    if (files) {
        Array.from(files).forEach(file => {
            if (galleryData.items.length < 9) {
                galleryData.items.add(file);
            }
        });
    }

    // Sync input files with accumulated DataTransfer files
    const fileInput = document.getElementById('gallery-upload');
    fileInput.files = galleryData.files;
    
    renderGalleryPreviews();
}

function renderGalleryPreviews() {
    const container = document.getElementById('gallery-preview-container');
    const addBtn = document.getElementById('gallery-add-btn');
    
    const oldPreviews = container.querySelectorAll('.gallery-item');
    oldPreviews.forEach(el => el.remove());

    Array.from(galleryData.files).forEach((file, index) => {
        const reader = new FileReader();
        reader.onload = function(e) {
            const div = document.createElement('div');
            div.className = 'gallery-item relative w-full aspect-square bg-gray-100 rounded overflow-hidden border border-gray-200 group';
            div.innerHTML = `<img src="${e.target.result}" class="absolute inset-0 w-full h-full object-contain bg-white sm:bg-gray-50 p-2">
                             <div class="absolute inset-0 bg-black bg-opacity-40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center pointer-events-none"></div>
                             <button type="button" onclick="removeNewGalleryImage(${index})" class="absolute top-1 right-1 bg-red-600 hover:bg-red-700 text-white p-1 rounded opacity-0 group-hover:opacity-100 transition-opacity shadow" title="Hapus">
                                 <i class='bx bx-trash text-xs'></i>
                             </button>
                             <div class="absolute bottom-1 right-1 bg-emerald-500 text-white text-[10px] px-1.5 py-0.5 rounded font-bold">Baru</div>`;
            container.insertBefore(div, addBtn);
        }
        reader.readAsDataURL(file);
    });
}

function removeNewGalleryImage(index) {
    const newData = new DataTransfer();
    Array.from(galleryData.files).forEach((file, i) => {
        if (i !== index) newData.items.add(file);
    });
    galleryData = newData;
    document.getElementById('gallery-upload').files = galleryData.files;
    renderGalleryPreviews();
}

// ─── Video Tab Switcher ────────────────────────────────────────────────
function switchVideoTab(tab) {
    const tabUrl  = document.getElementById('video-tab-url');
    const tabFile = document.getElementById('video-tab-file');
    const btnUrl  = document.getElementById('btn-tab-url');
    const btnFile = document.getElementById('btn-tab-file');

    if (tab === 'url') {
        tabUrl.classList.remove('hidden');
        tabFile.classList.add('hidden');
        btnUrl.className  = 'flex-1 text-[10px] font-semibold py-1 rounded border border-brand-500 bg-brand-500 text-white transition';
        btnFile.className = 'flex-1 text-[10px] font-semibold py-1 rounded border border-gray-300 bg-white text-gray-600 transition';
        // Reset file input supaya tidak ikut tersubmit
        const fi = document.getElementById('video_file_input');
        if (fi) fi.value = '';
    } else {
        tabUrl.classList.add('hidden');
        tabFile.classList.remove('hidden');
        btnFile.className = 'flex-1 text-[10px] font-semibold py-1 rounded border border-brand-500 bg-brand-500 text-white transition';
        btnUrl.className  = 'flex-1 text-[10px] font-semibold py-1 rounded border border-gray-300 bg-white text-gray-600 transition';
        // Reset URL input supaya tidak ikut tersubmit
        const ui = document.getElementById('video_url_input');
        if (ui) ui.value = '';
    }
}

// ─── Preview Video di area Foto Utama ─────────────────────────────────
function previewVideoFile(event) {
    const file = event.target.files[0];
    if (!file) return;

    // Update label filename
    const nameEl = document.getElementById('video-file-name');
    if (nameEl) nameEl.textContent = file.name + ' (' + (file.size / 1024 / 1024).toFixed(1) + ' MB)';

    // Tampilkan preview video di kontainer Foto Utama
    const container = document.getElementById('image-preview-container');
    const placeholder = document.getElementById('placeholder-text');
    const imgPreview = document.getElementById('image-preview');

    if (container) {
        // Hapus video preview lama jika ada
        const oldVideo = document.getElementById('video-preview-local');
        if (oldVideo) oldVideo.remove();

        const videoEl = document.createElement('video');
        videoEl.id = 'video-preview-local';
        videoEl.src = URL.createObjectURL(file);
        videoEl.controls = true;
        videoEl.className = 'absolute inset-0 w-full h-full object-contain bg-black';
        videoEl.style.zIndex = '15';
        container.appendChild(videoEl);

        if (placeholder) placeholder.style.display = 'none';
        if (imgPreview) imgPreview.classList.add('hidden');
    }
}
</script>
</x-app-layout>
